[metadata]
app = "torrust-tracker"
purpose = "configuration"
schema_version = "2.0.0"

[core.database]
driver = "mysql"
path = "mysql://db_user:db_user_secret_password@mysql:3306/torrust_tracker"

# Uncomment to enable services

#[[udp_trackers]]
#bind_address = "0.0.0.0:6969"

#[[http_trackers]]
#bind_address = "0.0.0.0:7070"

#[http_api]
#bind_address = "0.0.0.0:1212"

#[http_api.access_tokens]
#admin = "MyAccessToken"
