name: Publish crate

on:
  push:
    tags:
      - "v*"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    environment: crates-io-torrust
    outputs:
      publish: ${{ steps.check.outputs.publish }}
    steps:
      - id: check
        env:
          CRATES_TOKEN: "${{ secrets.CRATES_TOKEN }}"
        if: "${{ env.CRATES_TOKEN != '' }}"
        run: echo "publish=true" >> $GITHUB_OUTPUT

  test:
    needs: check-secret
    if: needs.check-secret.outputs.publish == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: cargo test

  publish:
    needs: test
    if: needs.check-secret.outputs.publish == 'true'
    runs-on: ubuntu-latest
    environment: crates-io-torrust
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Publish workspace packages
        run: |
          cargo publish -p torrust-tracker-located-error
          cargo publish -p torrust-tracker-primitives
          cargo publish -p torrust-tracker-configuration
          cargo publish -p torrust-tracker-test-helpers
          cargo publish -p torrust-tracker
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
